version: "3.9"
services:
  backend:
    container_name: backend_testing
    build:
      target: testing
    ports:
      - 9229:9229   # default debug port
    volumes:
      - ./srcs/backend/:/usr/src/app
    entrypoint: ["npm", "run", "test:e2e"]
    restart: unless-stopped
