version: "3.9"
services:
  backend:
    env_file: .env
    container_name: backend_dev
    build:
      context: ./backend/
      target: dev
    ports:
      - 3000:3000   # default port
      - 9229:9229   # default debug port
      - 3001:3001   # websockets
    networks:
      - webapp-network
    volumes:
      - ./backend/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "start:dev"]
    #entrypoint: ["sleep", "infinity"]
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:14.2
    ports:
      - 5432:5432
    networks:
      - webapp-network
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    logging:
      driver: none
    restart: always
    volumes:
      - pgadmindata:/var/tmp/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWD}
    networks:
      - webapp-network
    ports:
      - 5050:80
  frontend:
    container_name: frontend
    image: node:18-alpine
    ports:
      - 4200:4200
    networks:
      - webapp-network
    volumes:
      - ./frontend/:/usr/src/
    depends_on:     # ???
      - backend
    working_dir: /usr/src/
    # The first time, we entered the empty image,
    # installed angular cli, and generated new workspace with "ng new"
    command: sh -c "npm install && npm start"
    restart: unless-stopped

#  frontend:
#    container_name: frontend
#    build: ./frontend-app/
#    ports:
#      - "8080:80"
#      - "443:443"

networks:
  webapp-network:
    driver: bridge

volumes:
  dbdata: {}
  pgadmindata: {}
  node_modules: {} # tmp definition

