version: "3.9"
services:
  backend:
    container_name: backend_prod
    build:
      target: prod
    env_file: 
      - .env.production
    entrypoint: ["npm", "run", "start:prod"]
    restart: always

  frontend:
    container_name: web_app
    build:
      target: prod
    ports:
      - 80:80
      - 443:443
    entrypoint: ["nginx", "-g", "daemon off;"]
    restart: always
