version: "3.9"
services:
  backend:
    env_file: .env
    container_name: backend
    image: node:18-alpine
    ports:
      - 3000:3000   # default port
      - 3001:3001
      - 9229:9229   # default debug port
    networks:
      - webapp-network
    volumes:
      - ./backend/app:/usr/src/app
    depends_on:
      - db
    working_dir: /usr/src/app/api
    command: sh -c "npm install  && npm run start:dev"
    restart: unless-stopped
  db:
    container_name: db
    image: postgres:14.2
    ports:
      - 5432:5432
    networks:
      - webapp-network
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    logging:
      driver: none
    restart: always
    volumes:
      - pgadmindata:/var/tmp/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWD}
    networks:
      - webapp-network
    ports:
      - 5050:80

networks:
  webapp-network:
    driver: bridge

volumes:
  dbdata: {}
  pgadmindata: {}

