version: "3.9"
services:
  backend:
    env_file: .env
    container_name: backend_testing
    build:
      context: ./backend/
      target: testing
    ports:
      - 3000:3000   # default port
      - 9229:9229   # default debug port
      - 3001:3001   # websockets
    networks:
      - webapp-network
    volumes:
      - ./backend/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "test:e2e", "--config ./test/jest-e2e.json"]
    #entrypoint: ["sleep", "infinity"]
    restart: unless-stopped