# FROM node:18-alpine

# # ADD     ./app /usr/src/app

# # WORKDIR /usr/src/app

# # RUN npm install 

# EXPOSE 3000/tcp
# EXPOSE 9229/tcp

# ENTRYPOINT [ ["npm", "install"], ["npm", "run", "start:dev" ] ]
